### ISSUE TITLE
API call 

### ISSUE THREAD

**Issue by DenisKantic** [DenisKantic/weather_app_collab#13]
- [x] create function with the name "fetchApi" which is going to be used for fetching API ( fetch, .then... ) 
- [x] edit the if else function, if it's returning true, fetchAPI will be called. If it returns false, it will display user that input is incorrect 
- [x] in fetchAPI, for now just console.log the API call nothing more

URL for calling API : https://api.openweathermap.org/data/2.5/weather?q=${INPUT_VALUE}&units=metric&appid=${API_KEY}

**Comment by nedimmujcinovic** [comment]
I completed this tasks, let's go to the next story
