### ISSUE TITLE
DISPLAYING RESULTS OF API CALL 

### ISSUE THREAD

**Issue by DenisKantic** [DenisKantic/weather_app_collab#14]
In this section, you need to make new function which will be responsible for displaying results of api call. 
In that function, you need to forward api informations on our displayWeather container.

- [x] Create function called "displayWeather" 
- [x] set information in our html container from api call 
- [x] call this function in fetchAPI function, instead console.log

**Comment by nedimmujcinovic** [comment]
Thanks for your help. I finished all those points.
